[project]
name = "steganography"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "yafet", email = "yafet.com@proton.me" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
steganography = "steganography:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
